name: CI/CD to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | \
        docker login --username AWS --password-stdin <YOUR_ECR_URI>

    - name: Build Image
      run: docker build -t ci-cd-app .

    - name: Tag Image
      run: docker tag ci-cd-app:latest <YOUR_ECR_URI>:latest

    - name: Push Image
      run: docker push <YOUR_ECR_URI>:latest
